---
title: "Proposal"
author: "Rockets"
date: "2020/4/1"
output:
  html_document: default
  word_document: default
  pdf_document: default
pagemargins: 2.5
fontsize: 12
---

<style type=""Proposal/css">
	#header {
	    text-align: center;
	}
</style>

# 一.研究背景 
&emsp;&emsp;2019年底开始的新型冠状病毒率先在武汉爆发，并以我们始料未及的速度传播到其他地区和国家。我国各地疾病预防控制中心相继启动一级应急响应。由于各地对疫情的反应速度及采取的应对措施不用，疫情在各地的传播方式和速度也不一致。因此，研究我国各地疫情的传播趋势能较好的反映出各地政府公共卫生干预的效果。  

# 二.研究问题 
&emsp;&emsp;我们主要研究新冠肺炎在各地的实时传播强度，测度不同交通工具对疫情传播的影响，同时量化政府的干预措施对疫情发展的影响。  

# 三.数据来源 
1. 迁徙数据来源于[百度地图慧眼](http://qianxi.baidu.com/)。  
2. 新型冠状病毒疫情数据来源于狗熊会（公众号）。  
3. 航空旅行数据来源于[飞常准大数据平台](https://data.variflight.com/)。  
4. 铁路旅行数据来源于[高铁网车次查询](http://shike.gaotie.cn/)。  
5. 公路旅行数据来源于[汽车网汽车时刻查询](https://www.qichezhan.cn/)。
 
# 四.研究方法 
&emsp;&emsp;在本篇研究中，我们将采用动态模型对疫情传播进行分析，并采用逐点回归方法计算参数（具体方法根据后续研究确定）。  
 
# 五.问题及挑战 
1. 研究方法难。在有限时间里学习逐点回归方法。由于此法是属于非参数估计下的方法，有必要首先熟悉非参数方法领域。 
2. 数据整理难。我们需要整理从武汉到达全国各地的公路、铁路和航空数据及迁出数据，此项工作较繁琐，耗费较长。 
3. 模型理解难。除逐点回归方法外，我们仍需通篇理解林教授的动态模型思路，而由于此篇文章为外文文献，且多涉及数学领域，对我们有一定难度。 
 
# 六.解决办法 
1. 努力查找有关逐点回归的各种文献。 
2. 对于数据整理问题，小组内讨论分工，加大时间投入最终整理出所需数据。 
3. 对于模型理解问题，还需阅读相关文献，组员之间积极讨论，整理模型思路框架，必要时请教老师。 
 




